---
# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2
build:
    os: ubuntu-22.04
    tools:
        python: "3.12"
sphinx:
    configuration: docs/conf.py
formats:
    - pdf
    - epub
# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
    install:
    - requirements: doc-requirements.txt
