[build-system]
requires = ["uv-build>=0.11.12,<0.12"]
build-backend = "uv_build"

[project]
name = "django-improved-user"
version = "3.0.0rc1"
description = "Compose new Django User models that follow best-practices for international names and authenticate via email instead of username."
authors = [
    { name = "Russell Keith-Magee" },
    { name = "Andrew Pinkham" },
]
readme = "README.rst"
requires-python = ">=3.10"
dependencies = ["django>=4.2"]
license = { file = "LICENSE"}
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3 :: Only",
    "Framework :: Django",
    "Framework :: Django :: 4.2",
    "Framework :: Django :: 5.2",
    "Framework :: Django :: 6.0",
]

[project.urls]
Documentation = "https://django-improved-user.rtfd.io"
Source = "https://github.com/jambonrose/django-improved-user/"
Tracker = "https://github.com/jambonrose/django-improved-user/issues"

[project.optional-dependencies]
factory = [
    "factory-boy>=2.9",
    "Faker>=0.8",
    "python-dateutil>=2.6",
]

[dependency-groups]
dev = [
    "check-sdist>=0.1.0",
    "coverage>=6.2",
    "factory-boy>=3.2.1",
    "Faker>=11.3.0",
    "nox>=2024.4.15",
    "nox-uv>=0.7.1",
    "pylint>=2.12.2",
    "pylint-django>=2.5.0",
    "python-dateutil>=2.8.2",
]
docs = [
    "Django>=4.2,<4.3",
    "factory-boy>=3.2.1",
    "Sphinx>=7.4.7",
    "sphinx-rtd-theme>=2.0.0",
]
examples = [
    "django-coverage-plugin>=2.0.2",
    "django-extensions>=3.1.5",
    "factory-boy>=3.2.1",
]

[tool.uv.build-backend]
module-root = "src"
module-name = "improved_user"
source-include = [
    "*.md",
    "*.rst",
    ".coveragerc",
    ".flake8",
    ".isort.cfg",
    ".pylintrc",
    "LICENSE",
    "noxfile.py",
    "runtests.py",
    "setup.cfg",
    "tests/**",
    "uv.lock",
]

[tool.black]
line-length = 79
target-version = ['py310']
include = '\.pyi?$'

[tool.check-sdist]
default-ignore = true
git-only = [
    ".editorconfig",
    ".gitignore",
    ".ignore",
    ".prettierignore",
    ".prettierrc.toml",
    ".readthedocs.yaml",
    "docs/**",
    "example_extension_project/**",
    "example_integration_project/**",
    "example_replacement_project/**",
    "Makefile",
]
