name: Define Github labels
on:
    push:
        branches:
            - development
jobs:
    define:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - uses: micnncim/action-label-syncer@v1.3.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
