name: define github labels
on:
    push:
        branches:
            - main
jobs:
    define:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: micnncim/action-label-syncer@v1.3.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
